name: 'Set up node & dependencies'
description: 'Sets up a typical Node repo with Volta & Yarn caching'

runs:
  using: 'composite'
  steps:
    - uses: volta-cli/action@v1
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          **/node_modules
          **/.jest-cache
          **/.eslintcache
          **/.parcel-cache
          **/*.tsbuildinfo
          **/lib
          **/dist
        key: ${{ runner.os }}-yarn-v8-${{ hashFiles('**/package.json', '**/yarn.lock', '**/tsconfig.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-v7-
    - name: Install Dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --production false
