export const SET_QUESTION_SIZE_MSG = 'ƒ_SET_QUESTION_SIZE';
export const REQUEST_ANSWERS_MSG = 'ƒ_REQUEST_ANSWERS';
export const SET_ANSWERS_MSG = 'ƒ_SET_ANSWERS';
export const SET_ANSWER_VALUE_MSG = 'ƒ_SET_ANSWER_VALUE';
export const CLEAR_ANSWER_VALUE_MSG = 'ƒ_CLEAR_ANSWER_VALUE';
