export const SET_QUESTION_SIZE_MSG = 'SET_QUESTION_SIZE';
export const REQUEST_ANSWERS_MSG = 'REQUEST_ANSWERS';
export const SET_ANSWERS_MSG = 'SET_ANSWERS';
export const SET_ANSWER_VALUE_MSG = 'SET_ANSWER_VALUE';
export const CLEAR_ANSWER_VALUE_MSG = 'CLEAR_ANSWER_VALUE';
