const SET_QUESTION_SIZE_MSG = 'SET_QUESTION_SIZE';
const REQUEST_ANSWERS_MSG = 'REQUEST_ANSWERS';
const SET_ANSWERS_MSG = 'SET_ANSWERS';
const SET_ANSWER_VALUE_MSG = 'SET_ANSWER_VALUE';
const CLEAR_ANSWER_VALUE_MSG = 'CLEAR_ANSWER_VALUE';
