minVersion: '0.32.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js

releaseBranchPrefix: release/constants

requireNames:
  - /^formsort-constants-v.+\.tgz$/
targets:
  - name: npm
  - name: github
    tagPrefix: constants-
