minVersion: '0.32.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js
postReleaseCommand: node ../../scripts/post-release.js

releaseBranchPrefix: release/web-embed-api

requireNames:
  - /^formsort-.+\.tgz$/
targets:
  - name: npm
  - name: github
    tagPrefix: web-embed-api-
