minVersion: '0.31.0'
changelogPolicy: auto
preReleaseCommand: node ../../scripts/pre-release.js
postReleaseCommand: node ../../scripts/post-release.js

releaseBranchPrefix: release/tsconfig

requireNames:
  - /^formsort-.+\.tgz$/
targets:
  - name: npm
  - name: github
    tagPrefix: tsconfig-
